/**
 * ============================================================================
 * Main.styles.js  (v2.11.0 — Fase 3.5)
 * ============================================================================
 * Centraliza todos os StyleSheets do AcheiAqui_Main2.jsx.
 * Migrado 1:1 do monolito — zero alterações visuais.
 *
 * Exporta:
 *   editorS  — Menu / Inventory / Services editor forms
 *   configS  — Settings screen rows
 *   polS     — Accommodation policies
 *   photoS   — Photos manager grid
 *   spS      — SponsoredCard hero card
 *   hS       — Home screen (header, list, carousel, filters)
 *   acS      — Autocomplete dropdown
 *   fbS      — Active-filter badges strip
 *   sortS    — Sort bottom sheet
 *   afS      — Advanced filters panel
 *   profS    — Profile screen + owner overlay header
 *   bizS     — Business dashboard + cancel-sheet tokens
 *
 * NÃO incluídos aqui (permanecem locais ao componente):
 *   calS  — CalendarPicker (componente autónomo)
 *
 * NÃO incluídos aqui (já no Core):
 *   NAV_BAR_STYLES — exportado por AcheiAqui_Core (Fase 3)
 * ============================================================================
 */

import { StyleSheet, Platform, Dimensions } from 'react-native';

const { width: SCREEN_WIDTH } = Dimensions.get('window');

// ─────────────────────────────────────────────────────────────────────────────
// editorS
// ─────────────────────────────────────────────────────────────────────────────
export const editorS = StyleSheet.create({
  itemCard:          { backgroundColor:'#FFFFFF', borderRadius:12, padding:16, marginBottom:12, borderWidth:1, borderColor:'#EBEBEB' },
  itemHeader:        { flexDirection:'row', justifyContent:'space-between', alignItems:'flex-start', marginBottom:8 },
  itemName:          { fontSize:16, fontWeight:'700', color:'#111111', marginBottom:4 },
  itemCategory:      { fontSize:12, fontWeight:'600', color:'#8A8A8A', textTransform:'uppercase', letterSpacing:0.5 },
  itemPrice:         { fontSize:16, fontWeight:'800', color:'#D32323' },
  itemDescription:   { fontSize:13, color:'#8A8A8A', lineHeight:18, marginBottom:12 },
  itemActions:       { flexDirection:'row', gap:8, paddingTop:12, borderTopWidth:1, borderTopColor:'#EBEBEB' },
  itemActionBtn:     { flexDirection:'row', alignItems:'center', gap:6, paddingVertical:6, paddingHorizontal:12, borderRadius:8, backgroundColor:'#F7F7F8' },
  itemActionText:    { fontSize:12, fontWeight:'700', color:'#D32323' },
  emptyState:        { alignItems:'center', paddingVertical:60 },
  emptyStateTitle:   { fontSize:18, fontWeight:'700', color:'#111111', marginTop:16, marginBottom:8 },
  emptyStateText:    { fontSize:14, color:'#8A8A8A', textAlign:'center' },
  formOverlay:       { flex:1, backgroundColor:'rgba(0,0,0,0.7)', justifyContent:'flex-end', alignItems:'center' },
  formCard:          { backgroundColor:'#FFFFFF', borderTopLeftRadius:24, borderTopRightRadius:24, padding:20, paddingTop:16, width:'100%', maxHeight:'92%' },
  formTitle:         { fontSize:18, fontWeight:'800', color:'#111111', marginBottom:12, textAlign:'center' },
  formLabel:         { fontSize:12, fontWeight:'700', color:'#111111', marginBottom:6, marginTop:10 },
  formInput:         { borderWidth:1.5, borderColor:'#EBEBEB', borderRadius:10, padding:10, fontSize:14, color:'#111111', backgroundColor:'#FFFFFF' },
  formActions:       { flexDirection:'row', gap:10, marginTop:16, paddingBottom:8 },
  formBtnCancel:     { flex:1, paddingVertical:12, borderRadius:10, borderWidth:1.5, borderColor:'#EBEBEB', alignItems:'center' },
  formBtnCancelText: { fontSize:13, fontWeight:'700', color:'#8A8A8A' },
  formBtnSave:       { flex:1, paddingVertical:12, borderRadius:10, backgroundColor:'#D32323', alignItems:'center' },
  formBtnSaveText:   { fontSize:13, fontWeight:'700', color:'#FFFFFF' },
});

// ─────────────────────────────────────────────────────────────────────────────
// configS
// ─────────────────────────────────────────────────────────────────────────────
export const configS = StyleSheet.create({
  row:      { flexDirection:'row', alignItems:'center', paddingHorizontal:16, paddingVertical:14, backgroundColor:'#FFFFFF', borderBottomWidth:1, borderBottomColor:'#F2F2F2' },
  iconWrap: { width:40, height:40, borderRadius:10, alignItems:'center', justifyContent:'center', marginRight:14 },
  rowBody:  { flex:1 },
  rowTitle: { fontSize:15, fontWeight:'600', color:'#111111', marginBottom:2 },
  rowSub:   { fontSize:13, color:'#8A8A8A' },
});

// ─────────────────────────────────────────────────────────────────────────────
// polS
// ─────────────────────────────────────────────────────────────────────────────
export const polS = StyleSheet.create({
  sectionTitle:    { fontSize:16, fontWeight:'800', color:'#111111', marginBottom:12 },
  sectionDesc:     { fontSize:13, color:'#8A8A8A', lineHeight:18, marginBottom:16 },
  timeRow:         { flexDirection:'row', gap:10, marginBottom:4 },
  timeField:       { flex:1 },
  timeFieldSmall:  { width:80 },
  fieldLabel:      { fontSize:12, fontWeight:'600', color:'#8A8A8A', marginBottom:6 },
  timeInput:       { borderWidth:1.5, borderColor:'#EBEBEB', borderRadius:10, paddingVertical:10, paddingHorizontal:12, backgroundColor:'#FFFFFF', alignItems:'center' },
  timeValue:       { fontSize:15, fontWeight:'700', color:'#111111' },
  chipRow:         { flexDirection:'row', gap:8, flexWrap:'wrap', marginBottom:4 },
  chip:            { paddingHorizontal:16, paddingVertical:8, borderRadius:20, borderWidth:1.5, borderColor:'#EBEBEB', backgroundColor:'#FFFFFF' },
  chipActive:      { borderColor:'#D32323', backgroundColor:'#FFF0F0' },
  chipText:        { fontSize:13, fontWeight:'600', color:'#8A8A8A' },
  chipTextActive:  { color:'#D32323' },
  toggleRow:       { flexDirection:'row', alignItems:'center', paddingVertical:14, borderBottomWidth:1, borderBottomColor:'#F2F2F2' },
  toggleLabel:     { fontSize:14, fontWeight:'500', color:'#111111', marginBottom:2 },
  toggleDesc:      { fontSize:12, color:'#8A8A8A', lineHeight:16 },
  toggle:          { width:46, height:26, borderRadius:13, backgroundColor:'#DEDEDE', justifyContent:'center', paddingHorizontal:2 },
  toggleOn:        { backgroundColor:'#D32323' },
  toggleThumb:     { width:22, height:22, borderRadius:11, backgroundColor:'#FFFFFF', alignSelf:'flex-start' },
  toggleThumbOn:   { alignSelf:'flex-end' },
  roomBlockCard:   { backgroundColor:'#FFFFFF', borderRadius:14, padding:14, marginBottom:12, borderWidth:1, borderColor:'#EBEBEB' },
  roomBlockHeader: { flexDirection:'row', alignItems:'flex-start', marginBottom:10 },
  roomBlockName:   { fontSize:14, fontWeight:'700', color:'#111111', marginBottom:2 },
  roomBlockSub:    { fontSize:12, color:'#8A8A8A' },
  noBlocks:        { fontSize:13, fontWeight:'600', color:'#10B981' },
  hasBlocks:       { fontSize:13, fontWeight:'600', color:'#D32323' },
  blockItem:       { flexDirection:'row', alignItems:'center', gap:8, paddingVertical:6, borderTopWidth:1, borderTopColor:'#F2F2F2' },
  blockItemText:   { fontSize:13, color:'#555555', flex:1 },
  addBlockBtn:     { flexDirection:'row', alignItems:'center', gap:8, paddingVertical:12, borderWidth:1.5, borderColor:'#D32323', borderRadius:10, borderStyle:'dashed', justifyContent:'center', marginTop:8 },
  addBlockText:    { fontSize:13, fontWeight:'600', color:'#D32323' },
  addBlockForm:    { marginTop:8, gap:8 },
  blockInput:      { borderWidth:1.5, borderColor:'#EBEBEB', borderRadius:10, padding:10, fontSize:13, color:'#111111', backgroundColor:'#F7F7F8' },
});

// ─────────────────────────────────────────────────────────────────────────────
// photoS
// ─────────────────────────────────────────────────────────────────────────────
export const photoS = StyleSheet.create({
  countInfo:      { fontSize:14, fontWeight:'600', color:'#111111', marginBottom:14 },
  grid:           { flexDirection:'row', flexWrap:'wrap', gap:8 },
  gridItem:       { width:'48.5%', aspectRatio:1, borderRadius:12, overflow:'hidden', position:'relative' },
  gridPhoto:      { width:'100%', height:'100%' },
  capaBadge:      { position:'absolute', top:8, left:8, backgroundColor:'#D32323', borderRadius:6, paddingHorizontal:8, paddingVertical:3 },
  capaBadgeText:  { color:'#FFFFFF', fontSize:11, fontWeight:'700' },
  removeBtn:      { position:'absolute', top:8, right:8, width:24, height:24, borderRadius:12, backgroundColor:'rgba(0,0,0,0.55)', alignItems:'center', justifyContent:'center' },
  setCapaOverlay: { position:'absolute', bottom:0, left:0, right:0, backgroundColor:'rgba(0,0,0,0.45)', paddingVertical:8, alignItems:'center' },
  setCapaText:    { color:'#FFFFFF', fontSize:12, fontWeight:'600' },
  addBtn:         { flexDirection:'row', alignItems:'center', justifyContent:'center', gap:10, marginTop:16, paddingVertical:14, borderRadius:12, borderWidth:1.5, borderColor:'#D32323', backgroundColor:'#FFF0F0' },
  addBtnText:     { fontSize:14, fontWeight:'700', color:'#D32323' },
});

// ─────────────────────────────────────────────────────────────────────────────
// spS — SponsoredCard
// ─────────────────────────────────────────────────────────────────────────────
export const spS = StyleSheet.create({
  card:              { borderRadius:12, overflow:'hidden', backgroundColor:'#1a1a1a', shadowColor:'#000', shadowOffset:{width:0,height:4}, shadowOpacity:0.2, shadowRadius:8, elevation:6 },
  image:             { width:'100%', aspectRatio:16/9, justifyContent:'space-between' },
  imageFill:         { resizeMode:'cover' },
  scrim:             { ...StyleSheet.absoluteFillObject, backgroundColor:'rgba(0,0,0,0.30)' },
  topRow:            { flexDirection:'row', alignItems:'center', padding:12, gap:8 },
  sponsoredPill:     { backgroundColor:'#D32323', paddingHorizontal:10, paddingVertical:4, borderRadius:20 },
  sponsoredPillText: { fontSize:10, fontWeight:'800', color:'#FFFFFF', letterSpacing:0.5, textTransform:'uppercase' },
  premiumPill:       { backgroundColor:'rgba(0,0,0,0.5)', paddingHorizontal:10, paddingVertical:4, borderRadius:20, borderWidth:1, borderColor:'rgba(255,215,0,0.65)' },
  premiumPillText:   { fontSize:10, fontWeight:'700', color:'#FFD700' },
  infoStrip:         { backgroundColor:'rgba(0,0,0,0.58)', paddingHorizontal:14, paddingTop:12, paddingBottom:14, gap:4 },
  nameRow:           { flexDirection:'row', alignItems:'center', gap:6 },
  name:              { fontSize:18, fontWeight:'800', color:'#FFFFFF', flex:1, letterSpacing:-0.3 },
  category:          { fontSize:12, color:'rgba(255,255,255,0.75)', fontWeight:'500', marginBottom:2 },
  metaRow:           { flexDirection:'row', alignItems:'center', gap:5, flexWrap:'wrap' },
  ratingTxt:         { fontSize:13, fontWeight:'700', color:'#FFFFFF' },
  reviewsTxt:        { fontSize:11, color:'rgba(255,255,255,0.7)' },
  dot:               { width:3, height:3, borderRadius:1.5, backgroundColor:'rgba(255,255,255,0.4)', marginHorizontal:2 },
  statusDot:         { fontSize:8 },
  dotOpen:           { color:'#4ADE80' },
  dotClosed:         { color:'#F87171' },
  statusTxt:         { fontSize:11, fontWeight:'600' },
  statusOpen:        { color:'#4ADE80' },
  statusClosed:      { color:'#F87171' },
  promoBanner:       { flexDirection:'row', alignItems:'center', backgroundColor:'rgba(211,35,35,0.88)', borderRadius:6, paddingHorizontal:10, paddingVertical:6, marginTop:6, gap:6 },
  promoIcon:         { fontSize:13 },
  promoTxt:          { fontSize:12, fontWeight:'700', color:'#FFFFFF', flex:1 },
});

// ─────────────────────────────────────────────────────────────────────────────
// hS — Home screen
// ─────────────────────────────────────────────────────────────────────────────
export const hS = StyleSheet.create({
  container:              { flex:1, backgroundColor:'#F7F7F8', flexDirection:'column' },
  headerWrapper:          { backgroundColor:'#FFFFFF', zIndex:100, elevation:10, position:'relative' },
  header:                 { paddingHorizontal:16, paddingBottom:12, borderBottomWidth:1, borderBottomColor:'#EBEBEB' },
  headerTopRow:           { flexDirection:'row', alignItems:'center', justifyContent:'space-between', marginBottom:12 },
  versionRow:             { flexDirection:'row', alignItems:'center', flex:1 },
  versionText:            { fontSize:10, color:'#8A8A8A', fontWeight:'600', letterSpacing:0.3 },
  logo:                   { fontSize:20, fontWeight:'800', color:'#D32323', letterSpacing:-0.5 },
  headerActions:          { flexDirection:'row', gap:4 },
  headerActionBtn:        { width:34, height:34, borderRadius:17, backgroundColor:'#F7F7F8', alignItems:'center', justifyContent:'center', position:'relative' },
  notifBadge:             { position:'absolute', top:-2, right:-2, width:14, height:14, borderRadius:7, backgroundColor:'#D32323', alignItems:'center', justifyContent:'center', borderWidth:1.5, borderColor:'#FFFFFF' },
  notifBadgeText:         { fontSize:8, fontWeight:'800', color:'#FFFFFF' },
  searchBar:              { flexDirection:'row', borderWidth:1, borderColor:'#EBEBEB', borderRadius:10, backgroundColor:'#FFFFFF', overflow:'hidden' },
  searchColumn:           { flex:1, paddingVertical:7, paddingHorizontal:10 },
  searchDivider:          { width:1, backgroundColor:'#EBEBEB' },
  searchLabel:            { fontSize:9, color:'#8A8A8A', marginBottom:2, fontWeight:'600', letterSpacing:0.4, textTransform:'uppercase' },
  searchInput:            { fontSize:12, color:'#111111', paddingVertical:0, fontWeight:'500' },
  searchCloseBtn:         { width:28, height:28, borderRadius:14, backgroundColor:'#F7F7F8', alignItems:'center', justifyContent:'center', marginLeft:8 },
  categoryRowWrapper:     { backgroundColor:'#FFFFFF', borderBottomWidth:1, borderBottomColor:'#EBEBEB' },
  categoryRow:            { paddingHorizontal:16, paddingVertical:10, gap:8 },
  categoryChip:           { flexDirection:'row', alignItems:'center', borderWidth:1, borderColor:'#EBEBEB', borderRadius:20, paddingHorizontal:12, paddingVertical:7, backgroundColor:'#FFFFFF', gap:6 },
  categoryChipIconWrap:   { width:16, height:16, alignItems:'center', justifyContent:'center' },
  categoryChipLabel:      { fontSize:12, color:'#111111', fontWeight:'600', letterSpacing:-0.1 },
  scroll:                 { flex:1 },
  scrollContent:          { paddingBottom:80 },
  controlsSection:        { backgroundColor:'#FFFFFF', borderBottomWidth:1, borderBottomColor:'#EBEBEB' },
  unifiedFilterContainer: { paddingHorizontal:16, paddingTop:4, paddingBottom:4 },
  filterRow:              { flexDirection:'row', width:'100%', alignItems:'center' },
  filterItem:             { flex:1, flexDirection:'row', alignItems:'center', justifyContent:'center', paddingVertical:6, gap:5, minHeight:32 },
  filterItemActive:       { backgroundColor:'#FFF5F5', borderRadius:8 },
  filterItemText:         { fontSize:11, color:'#111111', fontWeight:'600', letterSpacing:-0.1 },
  filterItemTextActive:   { color:'#D32323' },
  filtersSpacer:          { height:1, backgroundColor:'#EBEBEB', marginVertical:2 },
  controlBadge:           { width:16, height:16, borderRadius:8, backgroundColor:'#D32323', alignItems:'center', justifyContent:'center', marginLeft:2 },
  controlBadgeText:       { fontSize:9, color:'#FFFFFF', fontWeight:'800' },
  sectionHeader:          { paddingHorizontal:16, paddingBottom:6, paddingTop:12, flexDirection:'row', justifyContent:'space-between', alignItems:'center' },
  sectionTitle:           { fontSize:15, fontWeight:'700', color:'#111111', letterSpacing:-0.3 },
  sectionCount:           { fontSize:11, color:'#8A8A8A', fontWeight:'500' },
  listCell:               { flexDirection:'row', backgroundColor:'#FFFFFF', marginHorizontal:16, marginBottom:8, borderRadius:14, padding:12, shadowColor:'#000', shadowOffset:{width:0,height:1}, shadowOpacity:0.06, shadowRadius:4, elevation:2 },
  listCellImage:          { width:72, height:72, borderRadius:10, marginRight:12, position:'relative', overflow:'hidden', backgroundColor:'#F7F7F8', alignItems:'center', justifyContent:'center' },
  listCellPhoto:          { width:'100%', height:'100%' },
  listCellIcon:           { fontSize:30 },
  listCellInfo:           { flex:1 },
  listCellTitleRow:       { flexDirection:'row', alignItems:'center', justifyContent:'space-between', marginBottom:3 },
  listCellTitle:          { fontSize:14, fontWeight:'700', color:'#111111', flex:1, letterSpacing:-0.2 },
  bookmarkBtn:            { padding:4, marginLeft:4 },
  listCellMeta:           { flexDirection:'row', alignItems:'center', marginBottom:3 },
  listCellRating:         { marginLeft:5, fontSize:12, fontWeight:'700', color:'#111111' },
  listCellReviews:        { marginLeft:3, fontSize:11, color:'#8A8A8A' },
  listCellCategory:       { fontSize:11, color:'#8A8A8A', marginBottom:6, fontWeight:'500' },
  listCellAddress:        { fontSize:11, color:'#8A8A8A', marginTop:2, fontWeight:'400' },
  amenitiesRow:           { flexDirection:'row', gap:5, marginBottom:6 },
  amenityChip:            { backgroundColor:'#F7F7F8', borderRadius:8, width:24, height:24, alignItems:'center', justifyContent:'center' },
  listCellFooter:         { flexDirection:'row', justifyContent:'space-between', marginTop:2, alignItems:'center' },
  listCellDistance:       { fontSize:11, color:'#8A8A8A', fontWeight:'500' },
  openText:               { fontSize:11, color:'#22A06B', fontWeight:'600' },
  closedText:             { fontSize:11, color:'#D32323', fontWeight:'600' },
  closingSoonText:        { fontSize:11, color:'#F59E0B', fontWeight:'600' },
  dealBadgeOverlay:       { position:'absolute', top:40, right:8, backgroundColor:'#D32323', paddingHorizontal:8, paddingVertical:4, borderRadius:12, zIndex:2, borderWidth:1.5, borderColor:'#FFFFFF', flexDirection:'row', alignItems:'center', gap:3 },
  dealBadgeText:          { fontSize:8, fontWeight:'800', color:'#FFFFFF', letterSpacing:0.2 },
  compareCheckbox:        { padding:4 },
  carouselSection:        { marginTop:12, marginBottom:4 },
  carouselHeader:         { paddingHorizontal:16, marginBottom:10, flexDirection:'row', alignItems:'center', justifyContent:'space-between' },
  carouselTitle:          { fontSize:12, fontWeight:'700', color:'#111111', letterSpacing:0.3, textTransform:'uppercase' },
  carouselDots:           { flexDirection:'row', gap:5, alignItems:'center' },
  carouselDot:            { width:5, height:5, borderRadius:2.5, backgroundColor:'#EBEBEB' },
  carouselDotActive:      { width:16, height:5, borderRadius:2.5, backgroundColor:'#D32323' },
  carouselScroll:         { paddingVertical:0 },
  carouselItem:           { width:SCREEN_WIDTH, paddingHorizontal:16 },
});

// ─────────────────────────────────────────────────────────────────────────────
// acS — Autocomplete dropdown
// ─────────────────────────────────────────────────────────────────────────────
export const acS = StyleSheet.create({
  backdrop:         { position:'absolute', top:Platform.select({android:168,ios:120,web:125,default:125}), left:0, right:0, bottom:0, backgroundColor:'rgba(0,0,0,0.3)', zIndex:999 },
  absoluteDropdown: { position:'absolute', top:Platform.select({android:168,ios:120,web:125,default:125}), left:0, right:0, maxHeight:400, zIndex:1000, elevation:5 },
  container:        { flex:1, backgroundColor:'#FFFFFF', borderBottomWidth:1, borderBottomColor:'#EBEBEB', shadowColor:'#000', shadowOffset:{width:0,height:2}, shadowOpacity:0.1, shadowRadius:4, elevation:5 },
  scroll:           { flex:1 },
  sectionTitle:     { fontSize:10, fontWeight:'700', color:'#8A8A8A', paddingHorizontal:16, paddingTop:12, paddingBottom:6, letterSpacing:0.8, textTransform:'uppercase' },
  item:             { flexDirection:'row', alignItems:'center', paddingVertical:12, paddingHorizontal:16, borderBottomWidth:1, borderBottomColor:'#EBEBEB', gap:10 },
  text:             { fontSize:13, color:'#111111', flex:1, fontWeight:'500' },
  recentHeader:     { flexDirection:'row', justifyContent:'space-between', alignItems:'center', paddingHorizontal:16, paddingTop:12, paddingBottom:2 },
  clearText:        { fontSize:11, color:'#D32323', fontWeight:'700' },
});

// ─────────────────────────────────────────────────────────────────────────────
// fbS — Active-filter badges strip
// ─────────────────────────────────────────────────────────────────────────────
export const fbS = StyleSheet.create({
  container:     { paddingBottom:8 },
  scroll:        { paddingHorizontal:16, gap:8 },
  badge:         { flexDirection:'row', alignItems:'center', backgroundColor:'#D32323', borderRadius:16, paddingVertical:6, paddingLeft:12, paddingRight:8, gap:6 },
  badgeText:     { fontSize:12, color:'#FFFFFF', fontWeight:'600' },
  badgeClose:    { width:16, height:16, borderRadius:8, backgroundColor:'rgba(255,255,255,0.3)', alignItems:'center', justifyContent:'center' },
  badgeCloseText:{ fontSize:10, color:'#FFFFFF', fontWeight:'700' },
});

// ─────────────────────────────────────────────────────────────────────────────
// sortS — Sort bottom sheet
// ─────────────────────────────────────────────────────────────────────────────
export const sortS = StyleSheet.create({
  sheet:               { backgroundColor:'#FFFFFF', borderTopLeftRadius:20, borderTopRightRadius:20, padding:20, paddingBottom:36 },
  title:               { fontSize:18, fontWeight:'800', color:'#111111', marginBottom:16 },
  sortOption:          { flexDirection:'row', alignItems:'center', justifyContent:'space-between', paddingVertical:16, borderBottomWidth:1, borderBottomColor:'#EBEBEB' },
  sortOptionText:      { fontSize:14, color:'#111111', fontWeight:'500' },
  sortOptionTextActive:{ fontWeight:'700', color:'#D32323' },
  sortCheck:           { fontSize:16, color:'#D32323' },
});

// ─────────────────────────────────────────────────────────────────────────────
// afS — Advanced filters panel
// ─────────────────────────────────────────────────────────────────────────────
export const afS = StyleSheet.create({
  panel:             { flex:1, backgroundColor:'#FFFFFF', marginTop:80, borderTopLeftRadius:28, borderTopRightRadius:28, shadowColor:'#000', shadowOffset:{width:0,height:-8}, shadowOpacity:0.08, shadowRadius:20, elevation:20 },
  header:            { flexDirection:'row', alignItems:'center', justifyContent:'space-between', padding:24, borderBottomWidth:1, borderBottomColor:'#EBEBEB' },
  title:             { fontSize:18, fontWeight:'800', color:'#111111', letterSpacing:-0.5 },
  close:             { fontSize:26, color:'#8A8A8A', fontWeight:'300' },
  scroll:            { flex:1, padding:20 },
  groupTitle:        { fontSize:14, fontWeight:'700', color:'#111111', marginBottom:12, marginTop:8 },
  closedToggleRow:   { flexDirection:'row', alignItems:'center', paddingVertical:16, marginBottom:12, borderBottomWidth:1, borderBottomColor:'#EBEBEB' },
  closedToggleLabel: { fontSize:15, fontWeight:'700', color:'#111111', marginBottom:2 },
  closedToggleDesc:  { fontSize:12, color:'#8A8A8A' },
  group:             { flexDirection:'row', flexWrap:'wrap', gap:8, marginBottom:20 },
  option:            { flexDirection:'row', alignItems:'center', gap:6, paddingVertical:8, paddingHorizontal:12, borderRadius:20, borderWidth:1, borderColor:'#EBEBEB', backgroundColor:'#FFFFFF' },
  optionActive:      { borderColor:'#D32323', backgroundColor:'#FFF0F0' },
  optionText:        { fontSize:12, color:'#111111', fontWeight:'600' },
  optionTextActive:  { color:'#D32323' },
  footer:            { flexDirection:'row', padding:20, gap:12, borderTopWidth:1, borderTopColor:'#EBEBEB' },
  clearBtn:          { flex:1, paddingVertical:14, alignItems:'center', borderRadius:12, borderWidth:1, borderColor:'#EBEBEB' },
  clearText:         { fontSize:14, fontWeight:'700', color:'#111111' },
  applyBtn:          { flex:1, paddingVertical:14, alignItems:'center', borderRadius:12, backgroundColor:'#D32323' },
  applyText:         { fontSize:14, fontWeight:'700', color:'#FFFFFF' },
});

// ─────────────────────────────────────────────────────────────────────────────
// profS — Profile screen + owner overlay
// ─────────────────────────────────────────────────────────────────────────────
export const profS = StyleSheet.create({
  overlay:                  { position:'absolute', left:0, right:0, backgroundColor:'#FFFFFF', zIndex:20000 },
  header:                   { backgroundColor:'#FFFFFF', paddingHorizontal:16, paddingTop:8, paddingBottom:12, flexDirection:'row', alignItems:'center', justifyContent:'space-between' },
  headerTitle:              { fontSize:17, fontWeight:'700', color:'#111111' },
  backBtn:                  { width:36, height:36, borderRadius:18, backgroundColor:'#F7F7F8', alignItems:'center', justifyContent:'center' },
  scroll:                   { flex:1, backgroundColor:'#FFFFFF' },
  topSection:               { alignItems:'center', paddingVertical:20, backgroundColor:'#FFFFFF' },
  avatarContainer:          { marginBottom:16 },
  avatarLarge:              { width:120, height:120, borderRadius:60, backgroundColor:'#F7F7F8', alignItems:'center', justifyContent:'center', borderWidth:3, borderColor:'#EBEBEB' },
  userName:                 { fontSize:26, fontWeight:'700', color:'#111111', marginBottom:12, letterSpacing:-0.5 },
  statsBadges:              { flexDirection:'row', gap:16 },
  statBadge:                { flexDirection:'row', alignItems:'center', backgroundColor:'#F7F7F8', paddingHorizontal:14, paddingVertical:8, borderRadius:20, gap:6 },
  statBadgeText:            { fontSize:14, fontWeight:'700', color:'#111111' },
  actionGrid:               { flexDirection:'row', flexWrap:'wrap', paddingHorizontal:16, paddingVertical:20, backgroundColor:'#FFFFFF' },
  actionButton:             { width:'25%', alignItems:'center', marginBottom:16 },
  actionIcon:               { width:56, height:56, borderRadius:28, backgroundColor:'#F7F7F8', alignItems:'center', justifyContent:'center', marginBottom:8 },
  actionLabel:              { fontSize:11, fontWeight:'500', color:'#111111', textAlign:'center', lineHeight:14, maxWidth:70 },
  divider:                  { height:8, backgroundColor:'#F7F7F8' },
  section:                  { paddingHorizontal:16, paddingVertical:20, backgroundColor:'#FFFFFF' },
  sectionTitle:             { fontSize:20, fontWeight:'700', color:'#111111', marginBottom:16, letterSpacing:-0.4 },
  recentlyViewedCard:       { flexDirection:'row', alignItems:'center', paddingVertical:12, borderBottomWidth:1, borderBottomColor:'#EBEBEB' },
  recentlyViewedPhoto:      { width:80, height:80, borderRadius:8, backgroundColor:'#F7F7F8', alignItems:'center', justifyContent:'center', marginRight:14, overflow:'hidden' },
  recentlyViewedPhotoImage: { width:80, height:80 },
  recentlyViewedIcon:       { fontSize:48 },
  recentlyViewedInfo:       { flex:1 },
  recentlyViewedName:       { fontSize:16, fontWeight:'600', color:'#111111', marginBottom:4, letterSpacing:-0.2 },
  recentlyViewedAddress:    { fontSize:13, fontWeight:'400', color:'#8A8A8A', lineHeight:18, marginBottom:2 },
  recentlyViewedMeta:       { fontSize:12, fontWeight:'400', color:'#8A8A8A' },
  menuRow:                  { flexDirection:'row', alignItems:'center', paddingVertical:16, borderBottomWidth:1, borderBottomColor:'#EBEBEB', gap:14 },
  menuLabel:                { fontSize:16, fontWeight:'500', color:'#111111', flex:1 },
  menuCount:                { fontSize:16, fontWeight:'600', color:'#8A8A8A', marginRight:8 },
});

// ─────────────────────────────────────────────────────────────────────────────
// bizS — Business dashboard + cancel-sheet shared tokens
// ─────────────────────────────────────────────────────────────────────────────
export const bizS = StyleSheet.create({
  premiumCard:              { backgroundColor:'#D32323', borderRadius:16, padding:20, marginHorizontal:16, marginVertical:12, shadowColor:'#000', shadowOffset:{width:0,height:4}, shadowOpacity:0.2, shadowRadius:8, elevation:6 },
  premiumCardContent:       { flexDirection:'row', alignItems:'center', gap:14 },
  premiumIcon:              { width:56, height:56, borderRadius:28, backgroundColor:'rgba(255,255,255,0.2)', alignItems:'center', justifyContent:'center' },
  premiumTitle:             { fontSize:18, fontWeight:'700', color:'#FFFFFF', marginBottom:4, letterSpacing:-0.3 },
  premiumDesc:              { fontSize:13, fontWeight:'500', color:'rgba(255,255,255,0.9)' },
  dashboardContent:         { flex:1, backgroundColor:'#F7F7F8' },
  businessHeader:           { backgroundColor:'#FFFFFF', paddingHorizontal:16, paddingTop:16, paddingBottom:16, borderBottomWidth:1, borderBottomColor:'#EBEBEB' },
  businessHeaderTop:        { flexDirection:'row', alignItems:'flex-start', marginBottom:16 },
  businessName:             { fontSize:22, fontWeight:'700', color:'#111111', letterSpacing:-0.4 },
  businessAddress:          { fontSize:13, fontWeight:'500', color:'#8A8A8A' },
  statusOverrideCard:       { flexDirection:'row', alignItems:'center', backgroundColor:'#F7F7F8', padding:14, borderRadius:12 },
  statusLabel:              { fontSize:12, fontWeight:'600', color:'#8A8A8A', textTransform:'uppercase', letterSpacing:0.5, marginBottom:4 },
  statusValue:              { fontSize:16, fontWeight:'700', color:'#111111' },
  statusSwitch:             { width:52, height:32, borderRadius:16, backgroundColor:'#EBEBEB', padding:2, justifyContent:'center' },
  statusSwitchActive:       { backgroundColor:'#22A06B' },
  statusSwitchKnob:         { width:28, height:28, borderRadius:14, backgroundColor:'#FFFFFF', shadowColor:'#000', shadowOffset:{width:0,height:2}, shadowOpacity:0.2, shadowRadius:3, elevation:3 },
  statusSwitchKnobActive:   { alignSelf:'flex-end' },
  metricsGrid:              { flexDirection:'row', flexWrap:'wrap', padding:12, gap:12 },
  metricCard:               { width:'48%', backgroundColor:'#FFFFFF', borderRadius:16, padding:16, alignItems:'center', shadowColor:'#000', shadowOffset:{width:0,height:2}, shadowOpacity:0.06, shadowRadius:8, elevation:2 },
  metricValue:              { fontSize:28, fontWeight:'700', color:'#111111', marginTop:8, marginBottom:4 },
  metricLabel:              { fontSize:13, fontWeight:'600', color:'#8A8A8A', marginBottom:6 },
  metricChange:             { fontSize:12, fontWeight:'700', color:'#D32323' },
  metricChangePositive:     { color:'#22A06B' },
  actionsSection:           { paddingHorizontal:16, paddingTop:12 },
  sectionTitle:             { fontSize:18, fontWeight:'700', color:'#111111', marginBottom:12, letterSpacing:-0.3 },
  actionCard:               { flexDirection:'row', alignItems:'center', backgroundColor:'#FFFFFF', borderRadius:12, padding:16, marginBottom:12, shadowColor:'#000', shadowOffset:{width:0,height:1}, shadowOpacity:0.04, shadowRadius:4, elevation:1 },
  actionIcon:               { width:44, height:44, borderRadius:22, backgroundColor:'#FFF0F0', alignItems:'center', justifyContent:'center', marginRight:14 },
  actionTitle:              { fontSize:16, fontWeight:'600', color:'#111111', marginBottom:3 },
  actionDesc:               { fontSize:13, fontWeight:'500', color:'#8A8A8A' },
  reviewsSection:           { marginTop:12, marginBottom:24 },
  reviewCard:               { backgroundColor:'#FFFFFF', borderRadius:12, padding:14, marginBottom:10, borderWidth:1, borderColor:'#EBEBEB' },
  reviewHeader:             { flexDirection:'row', justifyContent:'space-between', alignItems:'center', marginBottom:8 },
  reviewUser:               { fontSize:15, fontWeight:'600', color:'#111111' },
  reviewRating:             { fontSize:14, fontWeight:'700', color:'#D32323' },
  reviewText:               { fontSize:14, fontWeight:'400', color:'#111111', lineHeight:20, marginBottom:10 },
  reviewFooter:             { flexDirection:'row', justifyContent:'space-between', alignItems:'center' },
  reviewDate:               { fontSize:12, fontWeight:'500', color:'#8A8A8A' },
  replyButton:              { fontSize:13, fontWeight:'700', color:'#D32323' },
  repliedLabel:             { fontSize:12, fontWeight:'600', color:'#22A06B' },
  replyBubble:              { backgroundColor:'#F0F7F0', borderLeftWidth:3, borderLeftColor:'#22A06B', borderRadius:8, padding:10, marginBottom:10 },
  replyBubbleOwner:         { fontSize:12, fontWeight:'700', color:'#D32323' },
  replyBubbleText:          { fontSize:13, color:'#111111', lineHeight:18 },
  replyReviewPreview:       { backgroundColor:'#F7F7F8', borderRadius:12, padding:12, marginBottom:4, borderWidth:1, borderColor:'#EBEBEB' },
  replyPreviewUser:         { fontSize:14, fontWeight:'700', color:'#111111' },
  replyPreviewText:         { fontSize:13, color:'#8A8A8A', lineHeight:18 },
  replyTextInput:           { backgroundColor:'#F7F7F8', borderRadius:12, paddingHorizontal:14, paddingVertical:12, fontSize:14, color:'#111111', borderWidth:1.5, borderColor:'#EBEBEB', minHeight:100, textAlignVertical:'top', marginBottom:4 },
  replyCharCount:           { fontSize:11, color:'#8A8A8A', textAlign:'right', marginBottom:4 },
  promoManagerBanner:       { backgroundColor:'#FFF8E1', borderRadius:12, padding:14, marginBottom:16, borderWidth:1.5, borderColor:'#FFD54F' },
  promoManagerBannerLabel:  { fontSize:12, fontWeight:'700', color:'#F57F17', marginBottom:4 },
  promoManagerBannerText:   { fontSize:14, fontWeight:'600', color:'#111111' },
  promoItemCard:            { backgroundColor:'#FFFFFF', borderRadius:14, padding:14, marginBottom:12, borderWidth:1.5, borderColor:'#EBEBEB' },
  promoItemBadge:           { minWidth:52, height:52, borderRadius:10, backgroundColor:'#D32323', alignItems:'center', justifyContent:'center', paddingHorizontal:8 },
  promoItemBadgeText:       { fontSize:15, fontWeight:'800', color:'#FFFFFF' },
  promoItemTitle:           { fontSize:15, fontWeight:'700', color:'#111111', marginBottom:3 },
  promoItemDesc:            { fontSize:13, color:'#8A8A8A', lineHeight:18, marginBottom:4 },
  promoItemDates:           { fontSize:11, fontWeight:'500', color:'#8A8A8A' },
  promoToggle:              { width:44, height:26, borderRadius:13, backgroundColor:'#EBEBEB', justifyContent:'center', paddingHorizontal:3 },
  promoToggleActive:        { backgroundColor:'#22A06B' },
  promoToggleKnob:          { width:20, height:20, borderRadius:10, backgroundColor:'#FFFFFF', shadowColor:'#000', shadowOpacity:0.2, shadowRadius:2, elevation:2 },
  promoToggleKnobActive:    { alignSelf:'flex-end' },
  promoItemActions:         { flexDirection:'row', gap:10, marginTop:12, paddingTop:10, borderTopWidth:1, borderTopColor:'#EBEBEB' },
  promoItemBtn:             { flexDirection:'row', alignItems:'center', gap:5, paddingVertical:7, paddingHorizontal:14, borderRadius:8, borderWidth:1.5, borderColor:'#EBEBEB' },
  promoItemBtnText:         { fontSize:13, fontWeight:'600', color:'#D32323' },
  notifCard:                { backgroundColor:'#FFFFFF', borderRadius:12, padding:16, marginBottom:12, flexDirection:'row', alignItems:'flex-start', shadowColor:'#000', shadowOffset:{width:0,height:1}, shadowOpacity:0.04, shadowRadius:4, elevation:1 },
  notifCardUnread:          { backgroundColor:'#FFF0F0' },
  notifIcon:                { width:48, height:48, borderRadius:24, backgroundColor:'#F7F7F8', alignItems:'center', justifyContent:'center', marginRight:14 },
  notifTitle:               { fontSize:16, fontWeight:'700', color:'#111111', marginBottom:4 },
  notifMessage:             { fontSize:14, fontWeight:'400', color:'#111111', lineHeight:20, marginBottom:6 },
  notifTime:                { fontSize:12, fontWeight:'500', color:'#8A8A8A' },
  notifBadge:               { width:8, height:8, borderRadius:4, backgroundColor:'#D32323' },
  notifDetailIconWrap:      { width:72, height:72, borderRadius:36, backgroundColor:'#FFF0F0', alignItems:'center', justifyContent:'center', marginBottom:12 },
  notifDetailTitle:         { fontSize:20, fontWeight:'800', color:'#111111', marginBottom:4, textAlign:'center' },
  notifDetailTime:          { fontSize:13, fontWeight:'500', color:'#8A8A8A', textAlign:'center' },
  notifDetailMsgBox:        { backgroundColor:'#F7F7F8', borderRadius:12, padding:16, marginTop:4 },
  notifDetailMsg:           { fontSize:15, color:'#111111', lineHeight:22, textAlign:'center' },
  photosGrid:               { flexDirection:'row', flexWrap:'wrap', gap:8 },
  photoGridItem:            { width:'47%', aspectRatio:1, borderRadius:12, overflow:'hidden', position:'relative' },
  photoGridImg:             { width:'100%', height:'100%' },
  photoCoverBadge:          { position:'absolute', top:8, left:8, backgroundColor:'#D32323', borderRadius:6, paddingHorizontal:8, paddingVertical:3 },
  photoCoverBadgeText:      { fontSize:11, fontWeight:'700', color:'#FFFFFF' },
  photoRemoveBtn:           { position:'absolute', top:8, right:8, width:26, height:26, borderRadius:13, backgroundColor:'rgba(0,0,0,0.55)', alignItems:'center', justifyContent:'center' },
  photoSetCoverBtn:         { position:'absolute', bottom:8, left:8, right:8, backgroundColor:'rgba(0,0,0,0.55)', borderRadius:6, paddingVertical:5, alignItems:'center' },
  photoSetCoverText:        { fontSize:11, fontWeight:'700', color:'#FFFFFF' },
  couponCard:               { backgroundColor:'#FFFFFF', borderRadius:12, padding:14, marginBottom:10, shadowColor:'#000', shadowOffset:{width:0,height:1}, shadowOpacity:0.05, shadowRadius:4, elevation:1 },
  couponBadge:              { width:44, height:44, borderRadius:22, backgroundColor:'#FFF0F0', alignItems:'center', justifyContent:'center' },
  couponBadgeText:          { fontSize:13, fontWeight:'800', color:'#D32323' },
  couponCode:               { fontSize:16, fontWeight:'700', color:'#111111', letterSpacing:1 },
  couponMeta:               { fontSize:12, color:'#8A8A8A', marginTop:2 },
  couponFormCard:           { backgroundColor:'#FFFFFF', borderRadius:12, padding:16, marginTop:8, shadowColor:'#000', shadowOffset:{width:0,height:1}, shadowOpacity:0.05, shadowRadius:4, elevation:1 },
  settingsToggleRow:        { flexDirection:'row', alignItems:'center', paddingVertical:14, borderBottomWidth:1, borderBottomColor:'#EBEBEB' },
  settingsToggleLabel:      { fontSize:15, fontWeight:'600', color:'#111111', marginBottom:2 },
  settingsToggleDesc:       { fontSize:12, color:'#8A8A8A' },
  settingsCheckbox:         { width:24, height:24, borderRadius:6, borderWidth:2, borderColor:'#EBEBEB', alignItems:'center', justifyContent:'center' },
  settingsCheckboxActive:   { backgroundColor:'#D32323', borderColor:'#D32323' },
  settingsLocationBtn:      { flexDirection:'row', alignItems:'center', gap:6, backgroundColor:'#D32323', borderRadius:8, paddingVertical:10, paddingHorizontal:14, marginTop:8, alignSelf:'flex-start' },
  settingsLocationBtnText:  { fontSize:13, fontWeight:'700', color:'#FFFFFF' },
  typeGrid:                 { flexDirection:'row', flexWrap:'wrap', gap:8, marginTop:6 },
  typeChip:                 { flexDirection:'row', alignItems:'center', gap:6, paddingVertical:8, paddingHorizontal:12, borderRadius:20, borderWidth:1.5, borderColor:'#EBEBEB', backgroundColor:'#FFFFFF' },
  typeChipActive:           { borderColor:'#D32323', backgroundColor:'#FFF0F0' },
  typeChipIcon:             { fontSize:15 },
  typeChipLabel:            { fontSize:12, fontWeight:'600', color:'#111111' },
  typeChipLabelActive:      { color:'#D32323' },
  priceChip:                { paddingVertical:8, paddingHorizontal:16, borderRadius:12, borderWidth:1.5, borderColor:'#EBEBEB', backgroundColor:'#FFFFFF', alignItems:'center', minWidth:72 },
  priceChipActive:          { borderColor:'#D32323', backgroundColor:'#FFF0F0' },
  priceChipText:            { fontSize:14, fontWeight:'700', color:'#8A8A8A', letterSpacing:2 },
  priceChipTextActive:      { color:'#D32323' },
  highlightRow:             { flexDirection:'row', alignItems:'center', gap:8, marginBottom:10 },
  highlightRemoveBtn:       { width:32, height:32, borderRadius:16, backgroundColor:'#F7F7F8', alignItems:'center', justifyContent:'center' },
  highlightAddBtn:          { flexDirection:'row', alignItems:'center', gap:8, paddingVertical:12, paddingHorizontal:16, borderRadius:10, borderWidth:1.5, borderColor:'#D32323', borderStyle:'dashed', justifyContent:'center', marginTop:4 },
  highlightAddText:         { fontSize:14, fontWeight:'600', color:'#D32323' },
  hoursRow:                 { flexDirection:'row', alignItems:'center', gap:10, paddingVertical:12, borderBottomWidth:1, borderBottomColor:'#EBEBEB' },
  hoursToggle:              { width:36, height:20, borderRadius:10, backgroundColor:'#EBEBEB', justifyContent:'center', paddingHorizontal:2 },
  hoursToggleActive:        { backgroundColor:'#D32323' },
  hoursToggleKnob:          { width:16, height:16, borderRadius:8, backgroundColor:'#FFFFFF' },
  hoursToggleKnobActive:    { alignSelf:'flex-end' },
  hoursDay:                 { width:40, fontSize:14, fontWeight:'600', color:'#111111' },
  hoursInputsRow:           { flex:1, flexDirection:'row', alignItems:'center', gap:6 },
  hoursInput:               { flex:1, borderWidth:1.5, borderColor:'#EBEBEB', borderRadius:8, paddingHorizontal:10, paddingVertical:6, fontSize:14, color:'#111111', textAlign:'center' },
  hoursClosed:              { flex:1, fontSize:13, color:'#8A8A8A', fontStyle:'italic' },
  businessInfoCard:         { backgroundColor:'#FFFFFF', borderRadius:12, padding:16, marginTop:12, shadowColor:'#000', shadowOffset:{width:0,height:1}, shadowOpacity:0.04, shadowRadius:4, elevation:1 },
  infoCardTitle:            { fontSize:16, fontWeight:'700', color:'#111111', marginBottom:16 },
  infoRow:                  { flexDirection:'row', alignItems:'center', paddingVertical:14, borderBottomWidth:1, borderBottomColor:'#EBEBEB' },
  infoLabel:                { fontSize:12, fontWeight:'600', color:'#8A8A8A', marginBottom:4 },
  infoValue:                { fontSize:15, fontWeight:'500', color:'#111111' },
  reservationFilterRow:     { flexDirection:'row', paddingHorizontal:16, paddingVertical:12, gap:8, backgroundColor:'#FFFFFF', borderBottomWidth:1, borderBottomColor:'#EBEBEB' },
  reservationFilterBtn:     { flex:1, paddingVertical:10, paddingHorizontal:16, borderRadius:8, backgroundColor:'#F7F7F8', alignItems:'center' },
  reservationFilterBtnActive: { backgroundColor:'#D32323' },
  reservationFilterText:    { fontSize:14, fontWeight:'600', color:'#8A8A8A' },
  reservationFilterTextActive: { color:'#FFFFFF' },
  reservationCard:          { backgroundColor:'#FFFFFF', borderRadius:12, padding:16, marginBottom:12, shadowColor:'#000', shadowOffset:{width:0,height:2}, shadowOpacity:0.06, shadowRadius:8, elevation:2 },
  reservationHeader:        { flexDirection:'row', alignItems:'center', marginBottom:16 },
  reservationUserAvatar:    { width:56, height:56, borderRadius:28, backgroundColor:'#F7F7F8', alignItems:'center', justifyContent:'center', marginRight:14 },
  reservationUserName:      { fontSize:17, fontWeight:'700', color:'#111111', marginBottom:4 },
  reservationPhone:         { fontSize:13, fontWeight:'500', color:'#8A8A8A' },
  reservationStatusBadge:   { paddingHorizontal:12, paddingVertical:6, borderRadius:12, backgroundColor:'#22A06B' },
  reservationStatusBadgeCancelled: { backgroundColor:'#EBEBEB' },
  reservationStatusText:    { fontSize:12, fontWeight:'700', color:'#FFFFFF' },
  reservationStatusTextCancelled: { color:'#8A8A8A' },
  reservationDetails:       { gap:10, marginBottom:16 },
  reservationDetailRow:     { flexDirection:'row', alignItems:'center', gap:10 },
  reservationDetailText:    { fontSize:15, fontWeight:'500', color:'#111111' },
  reservationNotes:         { backgroundColor:'#F7F7F8', padding:12, borderRadius:8, marginBottom:16 },
  reservationNotesLabel:    { fontSize:12, fontWeight:'700', color:'#8A8A8A', marginBottom:6, textTransform:'uppercase', letterSpacing:0.5 },
  reservationNotesText:     { fontSize:14, fontWeight:'400', color:'#111111', lineHeight:20 },
  reservationFooter:        { flexDirection:'row', justifyContent:'space-between', alignItems:'center', paddingTop:12, borderTopWidth:1, borderTopColor:'#EBEBEB' },
  reservationCreatedAt:     { fontSize:12, fontWeight:'500', color:'#8A8A8A' },
  reservationActionBtn:     { width:36, height:36, borderRadius:18, backgroundColor:'#D32323', alignItems:'center', justifyContent:'center' },
  cancelReasonBadge:        { flexDirection:'row', alignItems:'center', gap:6, backgroundColor:'#FFF5F5', borderRadius:8, paddingHorizontal:10, paddingVertical:7, marginBottom:10, borderWidth:1, borderColor:'#FFCDD2' },
  cancelReasonBadgeText:    { fontSize:12, color:'#B71C1C', fontWeight:'500', flex:1 },
  amenitiesHint:            { fontSize:14, fontWeight:'400', color:'#8A8A8A', lineHeight:20, marginBottom:24, paddingHorizontal:4 },
  amenityCategory:          { marginBottom:28 },
  amenityCategoryTitle:     { fontSize:18, fontWeight:'700', color:'#111111', marginBottom:16, letterSpacing:-0.3 },
  amenityGrid:              { flexDirection:'row', flexWrap:'wrap', gap:12 },
  amenityItem:              { width:'47%', backgroundColor:'#FFFFFF', borderRadius:12, padding:14, borderWidth:2, borderColor:'#EBEBEB', alignItems:'center', minHeight:110 },
  amenityItemActive:        { borderColor:'#22A06B', backgroundColor:'#FFF0F0' },
  amenityIconCircle:        { width:48, height:48, borderRadius:24, backgroundColor:'#F7F7F8', alignItems:'center', justifyContent:'center', marginBottom:10 },
  amenityIconCircleActive:  { backgroundColor:'#22A06B' },
  amenityLabel:             { fontSize:13, fontWeight:'600', color:'#111111', textAlign:'center', lineHeight:18 },
  amenityLabelActive:       { color:'#D32323' },
  amenityCheck:             { position:'absolute', top:8, right:8 },
  modulesGrid:              { flexDirection:'row', flexWrap:'wrap', gap:12, marginTop:16 },
  moduleCard:               { width:'48%', backgroundColor:'#FFFFFF', borderRadius:16, padding:16, borderWidth:2, borderColor:'#EBEBEB', minHeight:180 },
  moduleCardActive:         { borderColor:'#22A06B', backgroundColor:'#FFF0F0' },
  moduleIconCircle:         { width:56, height:56, borderRadius:28, backgroundColor:'#F7F7F8', alignItems:'center', justifyContent:'center', marginBottom:12 },
  moduleIconCircleActive:   { backgroundColor:'#22A06B' },
  moduleLabel:              { fontSize:14, fontWeight:'700', color:'#111111', lineHeight:20, marginBottom:8 },
  moduleLabelActive:        { color:'#D32323' },
  moduleCheck:              { position:'absolute', top:12, right:12 },
  moduleActions:            { marginTop:8, paddingTop:8, borderTopWidth:1, borderTopColor:'#EBEBEB' },
  moduleActionText:         { fontSize:11, color:'#8A8A8A', marginBottom:4, fontWeight:'500' },
  promoPreviewCard:         { backgroundColor:'#F7F7F8', borderRadius:16, padding:16, marginBottom:20, borderWidth:1.5, borderColor:'#EBEBEB' },
  promoPreviewTop:          { flexDirection:'row', alignItems:'center', gap:8, marginBottom:12 },
  promoPreviewLabel:        { fontSize:13, fontWeight:'700', color:'#8A8A8A', textTransform:'uppercase', letterSpacing:0.5 },
  promoCodeDisplay:         { flexDirection:'row', alignItems:'center', justifyContent:'space-between', backgroundColor:'#FFFFFF', borderRadius:12, paddingHorizontal:16, paddingVertical:12, marginBottom:10, borderWidth:1.5, borderColor:'#FFD700' },
  promoCodeText:            { fontSize:26, fontWeight:'800', color:'#D32323', letterSpacing:3 },
  promoCopyBtn:             { flexDirection:'row', alignItems:'center', gap:4, backgroundColor:'#FFF0F0', borderRadius:8, paddingHorizontal:10, paddingVertical:6 },
  promoCopyText:            { fontSize:12, fontWeight:'700', color:'#D32323' },
  promoPreviewSub:          { fontSize:12, color:'#8A8A8A', lineHeight:17 },
  promoStatsRow:            { flexDirection:'row', gap:10, marginBottom:24 },
  promoStatCard:            { flex:1, backgroundColor:'#F7F7F8', borderRadius:12, paddingVertical:14, alignItems:'center', borderWidth:1, borderColor:'#EBEBEB' },
  promoStatValue:           { fontSize:20, fontWeight:'800', color:'#D32323' },
  promoStatLabel:           { fontSize:11, fontWeight:'600', color:'#8A8A8A', marginTop:3 },
  promoFormGroup:           { marginBottom:16 },
  promoFormLabel:           { fontSize:13, fontWeight:'700', color:'#111111', marginBottom:6 },
  promoFormInput:           { backgroundColor:'#F7F7F8', borderRadius:12, paddingHorizontal:14, paddingVertical:12, fontSize:15, color:'#111111', borderWidth:1.5, borderColor:'#EBEBEB' },
  promoActionRow:           { flexDirection:'row', gap:12, marginTop:8 },
  promoActionBtnGhost:      { flex:1, paddingVertical:14, borderRadius:12, borderWidth:1.5, borderColor:'#EBEBEB', alignItems:'center' },
  promoActionBtnGhostText:  { fontSize:14, fontWeight:'600', color:'#111111' },
  promoActionBtnPrimary:    { flex:2, paddingVertical:14, borderRadius:12, backgroundColor:'#D32323', alignItems:'center' },
  promoActionBtnPrimaryText:{ fontSize:14, fontWeight:'700', color:'#FFFFFF' },
  // Cancel Sheet tokens (usados no dashboard e no CancelReservationSheet)
  cancelSheet:              { backgroundColor:'#FFFFFF', borderTopLeftRadius:24, borderTopRightRadius:24, paddingHorizontal:20, paddingTop:12 },
  cancelSheetHandle:        { width:40, height:4, borderRadius:2, backgroundColor:'#EBEBEB', alignSelf:'center', marginBottom:20 },
  cancelSheetTitle:         { fontSize:18, fontWeight:'800', color:'#111111', marginBottom:4 },
  cancelSheetSubtitle:      { fontSize:13, color:'#8A8A8A', marginBottom:20 },
  cancelSheetLabel:         { fontSize:13, fontWeight:'700', color:'#111111', marginBottom:12, textTransform:'uppercase', letterSpacing:0.5 },
  cancelReasonOption:       { flexDirection:'row', alignItems:'center', gap:12, paddingVertical:13, paddingHorizontal:14, borderRadius:12, marginBottom:8, borderWidth:1.5, borderColor:'#EBEBEB', backgroundColor:'#FFFFFF' },
  cancelReasonOptionActive: { borderColor:'#E53935', backgroundColor:'#FFF5F5' },
  cancelReasonRadio:        { width:20, height:20, borderRadius:10, borderWidth:2, borderColor:'#EBEBEB', alignItems:'center', justifyContent:'center' },
  cancelReasonRadioActive:  { borderColor:'#E53935' },
  cancelReasonRadioDot:     { width:10, height:10, borderRadius:5, backgroundColor:'#E53935' },
  cancelReasonText:         { fontSize:14, fontWeight:'500', color:'#111111', flex:1 },
  cancelReasonTextActive:   { color:'#E53935', fontWeight:'600' },
  cancelReasonInput:        { backgroundColor:'#F7F7F8', borderRadius:12, paddingHorizontal:14, paddingVertical:12, fontSize:14, color:'#111111', borderWidth:1.5, borderColor:'#EBEBEB', minHeight:80, textAlignVertical:'top', marginTop:4, marginBottom:8 },
  cancelSheetActions:       { flexDirection:'row', gap:12, marginTop:16 },
  cancelSheetBtnGhost:      { flex:1, paddingVertical:14, borderRadius:12, borderWidth:1.5, borderColor:'#EBEBEB', alignItems:'center' },
  cancelSheetBtnGhostText:  { fontSize:14, fontWeight:'600', color:'#111111' },
  cancelSheetBtnPrimary:    { flex:2, paddingVertical:14, borderRadius:12, backgroundColor:'#E53935', alignItems:'center' },
  cancelSheetBtnPrimaryText:{ fontSize:14, fontWeight:'700', color:'#FFFFFF' },
});