import { StyleSheet } from 'react-native';
import { COLORS } from '../../core/AchAqui_Core';

export const s = StyleSheet.create({
  container: { flex: 1, backgroundColor: COLORS.white },
  header: {
    backgroundColor: COLORS.red,
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingBottom: 14,
  },
  exitBtn: {
    width: 36,
    height: 36,
    borderRadius: 18,
    backgroundColor: 'rgba(255,255,255,0.2)',
    alignItems: 'center',
    justifyContent: 'center',
  },
  headerBrand: { flex: 1, alignItems: 'center' },
  headerTitle: { fontSize: 18, fontWeight: '800', color: COLORS.white, letterSpacing: -0.5 },
  headerSub: {
    fontSize: 11,
    fontWeight: '600',
    color: 'rgba(255,255,255,0.75)',
    letterSpacing: 1,
    textTransform: 'uppercase',
  },
  tabBar: {
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grayLine,
    backgroundColor: COLORS.white,
  },
  tabItem: {
    flex: 1,
    alignItems: 'center',
    paddingVertical: 10,
    gap: 3,
    borderBottomWidth: 2,
    borderBottomColor: 'transparent',
  },
  tabItemActive: { borderBottomColor: COLORS.red },
  tabLabel: { fontSize: 10, fontWeight: '500', color: COLORS.grayText },
  tabLabelActive: { color: COLORS.red, fontWeight: '700' },
  filterRow: {
    flexDirection: 'row',
    gap: 8,
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grayLine,
  },
  filterRowCompact: {
    flexDirection: 'row',
    gap: 8,
    paddingHorizontal: 12,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grayLine,
  },
  filterChip: {
    paddingHorizontal: 12,
    paddingVertical: 4,
    borderRadius: 20,
    backgroundColor: COLORS.grayBg,
  },
  filterChipActive: { backgroundColor: COLORS.red },
  filterChipText: { fontSize: 13, fontWeight: '600', color: COLORS.grayText },
  filterChipTextActive: { color: COLORS.white },
  section: { paddingHorizontal: 16, paddingVertical: 16 },
  sectionTitle: { fontSize: 18, fontWeight: '700', color: COLORS.darkText, marginBottom: 14 },
  sectionCaption: { fontSize: 12, color: COLORS.grayText, marginTop: -8, marginBottom: 10 },
  divider: { height: 8, backgroundColor: COLORS.grayBg },
  rangeRow: { flexDirection: 'row', gap: 8, marginBottom: 12 },
  rangeChip: {
    paddingHorizontal: 10,
    paddingVertical: 5,
    borderRadius: 999,
    backgroundColor: COLORS.grayBg,
  },
  rangeChipActive: { backgroundColor: COLORS.red },
  rangeChipText: { fontSize: 12, color: COLORS.grayText, fontWeight: '600' },
  rangeChipTextActive: { color: COLORS.white },
  quickStatsRow: { marginTop: 10, gap: 2 },
  quickStatsText: { fontSize: 12, color: COLORS.grayText },
  kpiGrid: { flexDirection: 'row', flexWrap: 'wrap', gap: 10 },
  kpiCard: {
    flex: 1,
    minWidth: '45%',
    backgroundColor: COLORS.grayBg,
    borderRadius: 12,
    padding: 14,
    borderLeftWidth: 4,
  },
  kpiIcon: { fontSize: 24, marginBottom: 6 },
  kpiValue: { fontSize: 26, fontWeight: '800', letterSpacing: -1, marginBottom: 2 },
  kpiLabel: { fontSize: 12, color: COLORS.grayText, fontWeight: '500' },
  kpiTrend: { marginTop: 4, fontSize: 11, fontWeight: '700' },
  statsRow: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    paddingVertical: 10,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grayLine,
  },
  statsRowLabel: { fontSize: 14, color: COLORS.darkText },
  statsRowValue: { fontSize: 16, fontWeight: '700', color: COLORS.darkText },
  adminClaimCard: {
    backgroundColor: COLORS.grayBg,
    borderRadius: 12,
    padding: 14,
    marginBottom: 10,
  },
  adminClaimTop: { flexDirection: 'row', alignItems: 'flex-start', gap: 10, marginBottom: 8 },
  adminClaimBizName: { fontSize: 15, fontWeight: '700', color: COLORS.darkText, marginBottom: 2 },
  adminClaimSub: { fontSize: 12, color: COLORS.grayText },
  claimTimestamp: { fontSize: 11, color: COLORS.grayText, marginTop: 2 },
  claimMetaActions: { flexDirection: 'row', gap: 12, marginBottom: 8 },
  claimLink: { fontSize: 12, color: '#0EA5E9', fontWeight: '700' },
  claimResolvedAt: { fontSize: 11, color: COLORS.grayText, marginTop: 4 },
  adminClaimUser: { flexDirection: 'row', alignItems: 'center', gap: 6, marginBottom: 6 },
  adminClaimUserText: { fontSize: 13, color: COLORS.grayText },
  adminClaimEvidence: { fontSize: 12, color: COLORS.grayText, fontStyle: 'italic', lineHeight: 17, marginBottom: 8 },
  adminClaimActions: { flexDirection: 'row', gap: 10, marginTop: 4 },
  adminActionBtn: {
    flex: 1,
    paddingVertical: 10,
    borderRadius: 8,
    alignItems: 'center',
    justifyContent: 'center',
  },
  rejectBtn: { backgroundColor: COLORS.white, borderWidth: 1, borderColor: COLORS.red },
  approveBtn: { backgroundColor: COLORS.green },
  rejectBtnText: { fontSize: 13, fontWeight: '700', color: COLORS.red },
  approveBtnText: { fontSize: 13, fontWeight: '700', color: COLORS.white },
  statusBadge: { borderRadius: 8, paddingHorizontal: 8, paddingVertical: 4 },
  statusBadgeText: { fontSize: 12, fontWeight: '700' },
  adminNoteBox: { padding: 8, backgroundColor: '#FFF7ED', borderRadius: 8, marginBottom: 6 },
  adminNoteLabel: { fontSize: 12, color: '#92400E' },
  noteModalOverlay: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0,0,0,0.5)',
    justifyContent: 'center',
    alignItems: 'center',
    padding: 20,
  },
  noteModal: {
    backgroundColor: COLORS.white,
    borderRadius: 16,
    padding: 20,
    width: '100%',
  },
  noteModalTitle: { fontSize: 17, fontWeight: '700', color: COLORS.darkText, marginBottom: 4 },
  noteModalSub: { fontSize: 13, color: COLORS.grayText, marginBottom: 10 },
  noteInput: {
    backgroundColor: COLORS.grayBg,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
    fontSize: 14,
    color: COLORS.darkText,
    minHeight: 80,
  },
  noteModalCancelBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: COLORS.grayBg,
    alignItems: 'center',
  },
  noteModalConfirmBtn: {
    flex: 1,
    paddingVertical: 12,
    borderRadius: 10,
    alignItems: 'center',
    backgroundColor: COLORS.green,
  },
  bizRow: {
    flexDirection: 'row',
    alignItems: 'center',
    paddingHorizontal: 16,
    paddingVertical: 12,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grayLine,
  },
  bizRowName: { fontSize: 14, fontWeight: '600', color: COLORS.darkText, marginBottom: 2 },
  bizRowSub: { fontSize: 12, color: COLORS.grayText, marginBottom: 2 },
  bizRowMeta: { fontSize: 11, color: COLORS.grayText },
  claimedDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.green },
  metaText: { fontSize: 12, color: COLORS.grayText, paddingHorizontal: 16, paddingVertical: 8 },
  roleBadge: { borderRadius: 6, paddingHorizontal: 6, paddingVertical: 2 },
  roleBadgeText: { fontSize: 11, fontWeight: '700' },
  loadMoreBtn: {
    margin: 16,
    paddingVertical: 12,
    borderRadius: 10,
    backgroundColor: COLORS.grayBg,
    alignItems: 'center',
  },
  loadMoreText: { fontSize: 14, fontWeight: '600', color: COLORS.darkText },
  searchBoxInTab: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    marginHorizontal: 16,
    marginVertical: 10,
    backgroundColor: COLORS.grayBg,
    borderRadius: 10,
    paddingHorizontal: 12,
    paddingVertical: 10,
  },
  searchInputInTab: { flex: 1, fontSize: 14, color: COLORS.darkText },
  importBtn: {
    width: 44,
    height: 44,
    borderRadius: 10,
    backgroundColor: COLORS.red,
    alignItems: 'center',
    justifyContent: 'center',
    marginVertical: 10,
  },
  filterScrollRow: { paddingVertical: 3, borderBottomWidth: 1, borderBottomColor: COLORS.grayLine },
  rowActions: { flexDirection: 'row', alignItems: 'center', gap: 4, marginLeft: 8 },
  actionIconBtn: {
    width: 34,
    height: 34,
    borderRadius: 8,
    backgroundColor: COLORS.grayBg,
    alignItems: 'center',
    justifyContent: 'center',
  },
  emptyState: { flex: 1, alignItems: 'center', justifyContent: 'center', padding: 40 },
  emptyTitle: { fontSize: 18, fontWeight: '700', color: COLORS.darkText, marginBottom: 8, textAlign: 'center' },
  emptyText: { fontSize: 14, color: COLORS.grayText, textAlign: 'center', lineHeight: 20 },
  activityRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 8,
    paddingVertical: 8,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grayLine,
  },
  activityDot: { width: 8, height: 8, borderRadius: 4, backgroundColor: COLORS.red },
  activityTitle: { fontSize: 13, color: COLORS.darkText, fontWeight: '600' },
  activitySub: { fontSize: 12, color: COLORS.grayText },
  activityTime: { fontSize: 11, color: COLORS.grayText, marginLeft: 6 },
  historyClaimRow: {
    paddingVertical: 9,
    borderBottomWidth: 1,
    borderBottomColor: COLORS.grayLine,
  },
  historyClaimTitle: { fontSize: 13, color: COLORS.darkText, fontWeight: '700' },
  historyClaimSub: { fontSize: 12, color: COLORS.grayText, marginTop: 2 },
  sparklineRow: {
    marginTop: 8,
    height: 80,
    flexDirection: 'row',
    alignItems: 'flex-end',
    gap: 4,
  },
  sparkBar: {
    width: 8,
    borderRadius: 3,
    backgroundColor: '#F97316',
  },
  alertCard: {
    backgroundColor: '#FFF7ED',
    borderRadius: 12,
    padding: 12,
    marginBottom: 8,
    borderWidth: 1,
    borderColor: '#FED7AA',
  },
  alertTitle: { fontSize: 13, fontWeight: '700', color: '#9A3412' },
  alertSub: { fontSize: 12, color: '#9A3412', marginTop: 4 },
});
